<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp3.1</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.SignalR.Client" Version="3.1.26" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Osmos.Business.Common\Osmos.Business.Common.csproj" />
    <ProjectReference Include="..\Osmos.Business.Data.NoSql\Osmos.Business.Data.NoSql.csproj" />
    <ProjectReference Include="..\Osmos.Workers.Common\Osmos.Workers.Common.csproj" />
    <ProjectReference Include="..\Osmos.Workers.Helpers.Eth\Osmos.Workers.Helpers.Eth.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="appsettings.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
